Refactor Azure authentication and test suite
- Remove Test-WebhookExecutorIntegration from main test target for independent execution
- Fix shellcheck SC2115 warning in Test-WebhookDeploymentPreparation using ${var:?} syntax
- Update Azure auth to fetch client ID/tenant ID from service principal display name
- Remove AZURE_CLIENT_ID and AZURE_TENANT_ID from compose environment variables
- Update documentation and man pages accordingly

diff --git a/test/Test-WebhookExecutorIntegration b/test/Test-WebhookExecutorIntegration
--- a/test/Test-WebhookExecutorIntegration
+++ b/test/Test-WebhookExecutorIntegration
@@ -8,7 +8,7 @@
 # Test-WebhookExecutorIntegration - Test webhook hook responses inside the container via webhook service
 # shellcheck source=../bin/Declare-BashScript
 
-source "$(dirname "$0")/../bin/Declare-BashScript" "$0" "command:,jwt:,destination:,webhook-url:,help" "h" "$@"
+source "$(dirname "$0")/../bin/Declare-BashScript" "$0" "help,command:,destination:,keyvault-url:,secret-name:,service-principal-name:,service-principal-password:,webhook-url:" "h" "$@"
 
 ###########
 # Variables
@@ -46,7 +46,7 @@ function test_command {
 # Arguments
 ###########
 
-declare -r synopsis="${script_name} --webhook-url URL --destination DESTINATION --command CMD [--command CMD ...] [--help]"
+declare -r synopsis="${script_name} --help | --webhook-url URL --destination DESTINATION --keyvault-url URL --secret-name NAME --service-principal-name NAME --service-principal-password PASSWORD --command CMD [--command CMD ...]"
 eval set -- "$script_arguments"
 declare -a commands=()
 
@@ -59,12 +59,24 @@ while [[ $# -gt 0 ]]; do
         commands+=("$2")
         shift 2
         ;;
-    --jwt)
-        declare -r jwt="$2"
-        shift 2
-        ;;
     --destination)
         declare -r destination="$2"
+        shift 2
+        ;;
+    --keyvault-url)
+        declare -r keyvault_url="$2"
+        shift 2
+        ;;
+    --secret-name)
+        declare -r secret_name="$2"
+        shift 2
+        ;;
+    --service-principal-name)
+        declare -r service_principal_name="$2"
+        shift 2
+        ;;
+    --service-principal-password)
+        declare -r service_principal_password="$2"
         shift 2
         ;;
     --webhook-url)
@@ -84,6 +96,26 @@ done
 ((${#commands[@]} > 0)) || error 1 "At least one command to test is required."
 [[ -n ${destination:-} ]] || error 1 "A non-blank value for destination is required."
 [[ -n ${webhook_url:-} ]] || error 1 "A non-blank value for webhook-url is required."
+[[ -n ${service_principal_name:-} ]] || error 1 "A non-blank value for service-principal-name is required."
+[[ -n ${service_principal_password:-} ]] || error 1 "A non-blank value for service-principal-password is required."
+[[ -n ${keyvault_url:-} ]] || error 1 "A non-blank value for keyvault-url is required."
+[[ -n ${secret_name:-} ]] || error 1 "A non-blank value for secret-name is required."
+
+# Fetch AZURE_CLIENT_ID and AZURE_TENANT_ID from service principal display name
+
+sp_info=$(az ad sp list --display-name "$service_principal_name" --query "[].{appId:appId, appOwnerTenantId:appOwnerTenantId}" -o json | jq -r '.[0]')
+
+if [[ -z "$sp_info" || "$sp_info" == "null" ]]; then
+    error 1 "Service principal '$service_principal_name' not found."
+fi
+
+export AZURE_CLIENT_ID=$(echo "$sp_info" | jq -r '.appId') AZURE_TENANT_ID=$(echo "$sp_info" | jq -r '.appOwnerTenantId')
+
+# Fetch JWT from Key Vault
+
+declare -r jwt=$(./bin/Get-JsonWebToken --keyvault-url "$keyvault_url" --secret-name "$secret_name") || {
+    error 1 "Failed to fetch JSON Web Token from $keyvault_url"
+}
 
 ###########
 # Main
